name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "src"
          - "tests"
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: "18"
        check-path: ${{ matrix.path }}
